pre-commit:
  parallel: true
  commands:
    biome:
      glob: "*.{ts,tsx,js,jsx,json}"
      run: bunx biome format --write {staged_files}
      stage_fixed: true
    typecheck:
      run: bun tsc --noEmit

commit-msg:
  commands:
    commitlint:
      run: bunx commitlint --edit {1}
